name: Tser CI

on:
  push:
    branches:
      - master

jobs:
  # 发布到 GitHub Pages
  # build-and-deploy-to-github-pages:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@master

  #     - name: Build and Deploy to GitHub Pages
  #       uses: JamesIves/github-pages-deploy-action@master
  #       env:
  #         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  #         BRANCH: gh-pages
  #         FOLDER: build
  #         BUILD_SCRIPT: npm install && npm run build

  # 发布到服务器
  build-and-deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: npm install
        env:
          CI: true

      - name: Build Project
        run: npm run build
        env:
          CI: true

      # 打印当前工作目录
      - name: Run a one-line script
        run: pwd

      # 上传dist目录作为制品
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.1.3
        with:
          # 制品名称
          name: artifact # optional, default is artifact
          # 一个文件, 一个目录 或者 通配符模式 上传
          path: dist
