# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Run a one-line script
        run: pwd

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.1.3
        with:
          # 制品名称
          name: artifact # optional, default is artifact
          # 一个文件, 一个目录 或者 通配符模式 上传
          path: dist
